version: BuildNr.{build}

image: Visual Studio 2015

shallow_clone: true

clone_folder: c:\projects\visualization.vortex

environment:
  app_id: visualization.vortex

  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Release
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release
      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.16299.0"
    - GENERATOR: "Visual Studio 14 ARM"
      CONFIG: Release
      WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.16299.0"

build_script:
  - cd ..
  - git clone --depth=1 --branch master https://github.com/xbmc/xbmc.git
  - cd %app_id%
  - mkdir build
  - cd build
  - cmake -T host=x64 -G "%GENERATOR%" %WINSTORE% -DADDONS_TO_BUILD=%app_id% -DCMAKE_BUILD_TYPE=%CONFIG% -DADDON_SRC_PREFIX=../.. -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
  - cmake --build . --config %CONFIG% --target %app_id%
